### ISSUE TITLE
How do use this package?

### ISSUE THREAD

**Issue by 7ammer** [griffithstek/nativescript-ad-support#7]
Hello,
Many thanks for creating this! :)
Quick question. Do I simply need to install this package or do I also need to run some function to initiate something?

Cheers

**Comment by griffithstek** [comment]
You just install it and it automatically adds the framework when it builds for iOS. You can open the project in Xcode to verify the framework has been added.

**Comment by 7ammer** [comment]
Super! Thanks @griffithstek :)
